michaelthomasletts/boto3-refresh-session

- bump_version.py
Releasing a minor version update as this package should finally be ready to escape the beta level.
> [minor] Finishing touches to the package.

- .github/workflows/pull_request.yml
> Updated pull_request actions config to avoid concurrent workflow triggers.

- boto3_refresh_session/session.py
I added a logger to session.py …
> Adding logger with log messages.

- boto3_refresh_session/session.py
- tests/test_session.py
> updating logging

- boto3_refresh_session/session.py
> importing changes

- boto3_refresh_session/session.py
> Updating logic for logging

- README.md
- doc/index.rst
- pyproject.toml
> updated description

- README.md
> Minor README suggestion.

- .github/pull_request_template.md
- README.md
- boto3_refresh_session/__init__.py
- boto3_refresh_session/session.py
- doc/authorization.rst
- doc/index.rst
- doc/reference/session/boto3_refresh_session.session.rst
- pyproject.toml
- tests/test_session.py
> [major] Removing attrs, renaming to RefreshableSession, and modifying docs.

- README.md
- doc/index.rst
> modified examples

- boto3_refresh_session/session.py
> fixed small error

- .github/workflows/push.yml
- boto3_refresh_session/__init__.py
- bump_version.py
> adding version dunder

- boto3_refresh_session/__init__.py
- bump_version.py
> added shebang

- boto3_refresh_session/__init__.py
> updated __all__

- README.md
- boto3_refresh_session/session.py
- doc/index.rst
> added warning and doc changes

- doc/authors.rst
- doc/index.rst
- doc/raison.rst
- doc/usage.rst
> significant doc changes

- doc/usage.rst
> adding ref

- .github/workflows/push.yml
> workflow update

- doc/usage.rst
> enhancing usage section docs

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
> removing perms

- boto3_refresh_session/custom.py
- boto3_refresh_session/ecs.py
- boto3_refresh_session/session.py
- boto3_refresh_session/sts.py
> [minor] Added TemporaryCredentials typed dict.

- README.md
> PyPI does not support emoji shortcuts.

- README.md
- boto3_refresh_session/methods/iot/x509.py
- boto3_refresh_session/utils/typing.py
- doc/modules/iot.rst
- pyproject.toml
The following PR allows users to interact with `RefreshableSession(method="iot", ...)` such that they can subscribe, receive, and publish messages via MQTT.
> [minor] Adding `mqtt` method to IOTX509RefreshableSession
